name: "Build GH Pages"

on:
  push:
    branches:
      - main

jobs:
  update-images:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci(debug)')"
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd website
          npm install
          npm run-script build
        env:
          REACT_APP_GA_CODE: ${{ secrets.REACT_APP_GA_CODE }}
          REACT_APP_FORM_SCAN: ${{ secrets.REACT_APP_FORM_SCAN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website/build